<?php

namespace ContainerSXXBo5p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRendementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RendementController' shared autowired service.
     *
     * @return \App\Controller\RendementController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RendementController'] = $instance = new \App\Controller\RendementController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\RendementController', $container));

        return $instance;
    }
}
