<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uvux0ciService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uvux0ci' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uvux0ci'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'riskService' => ['privates', 'App\\Service\\RiskScoringService', 'getRiskScoringServiceService', true],
        ], [
            'riskService' => 'App\\Service\\RiskScoringService',
        ]);
    }
}
