<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4bU_ZGXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4bU.ZGX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4bU.ZGX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entrepriseRepository' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
            'investissementRepository' => ['privates', 'App\\Repository\\InvestissementRepository', 'getInvestissementRepositoryService', true],
            'operationRepository' => ['privates', 'App\\Repository\\OperationRepository', 'getOperationRepositoryService', true],
            'rendementRepository' => ['privates', 'App\\Repository\\RendementInvestissementRepository', 'getRendementInvestissementRepositoryService', true],
            'tresorerieRepository' => ['privates', 'App\\Repository\\TresorerieRepository', 'getTresorerieRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'entrepriseRepository' => 'App\\Repository\\EntrepriseRepository',
            'investissementRepository' => 'App\\Repository\\InvestissementRepository',
            'operationRepository' => 'App\\Repository\\OperationRepository',
            'rendementRepository' => 'App\\Repository\\RendementInvestissementRepository',
            'tresorerieRepository' => 'App\\Repository\\TresorerieRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
