<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fgm2hIfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fgm2hIf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fgm2hIf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'investissementRepository' => ['privates', 'App\\Repository\\InvestissementRepository', 'getInvestissementRepositoryService', true],
            'rendementRepository' => ['privates', 'App\\Repository\\RendementInvestissementRepository', 'getRendementInvestissementRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'investissementRepository' => 'App\\Repository\\InvestissementRepository',
            'rendementRepository' => 'App\\Repository\\RendementInvestissementRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
