<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FujbCKhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FujbCKh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FujbCKh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiService' => ['privates', 'App\\Service\\Api\\AiAssistantService', 'getAiAssistantServiceService', true],
        ], [
            'aiService' => 'App\\Service\\Api\\AiAssistantService',
        ]);
    }
}
