<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nqb5Ce0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nqb5Ce0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nqb5Ce0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiService' => ['privates', 'App\\Service\\Api\\AiAssistantService', 'getAiAssistantServiceService', true],
            'invRepo' => ['privates', 'App\\Repository\\InvestissementRepository', 'getInvestissementRepositoryService', true],
            'rendRepo' => ['privates', 'App\\Repository\\RendementInvestissementRepository', 'getRendementInvestissementRepositoryService', true],
        ], [
            'aiService' => 'App\\Service\\Api\\AiAssistantService',
            'invRepo' => 'App\\Repository\\InvestissementRepository',
            'rendRepo' => 'App\\Repository\\RendementInvestissementRepository',
        ]);
    }
}
