<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiAssistantServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Api\AiAssistantService' shared autowired service.
     *
     * @return \App\Service\Api\AiAssistantService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Api\\AiAssistantService'] = new \App\Service\Api\AiAssistantService();
    }
}
