<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiAdvisorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\AiAdvisorController' shared autowired service.
     *
     * @return \App\Controller\Api\AiAdvisorController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\AiAdvisorController'] = $instance = new \App\Controller\Api\AiAdvisorController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\AiAdvisorController', $container));

        return $instance;
    }
}
