<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvestissementApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\InvestissementApiController' shared autowired service.
     *
     * @return \App\Controller\Api\InvestissementApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\InvestissementApiController'] = $instance = new \App\Controller\Api\InvestissementApiController(($container->privates['App\\Repository\\InvestissementRepository'] ?? $container->load('getInvestissementRepositoryService')), ($container->privates['App\\Repository\\EntrepriseRepository'] ?? $container->load('getEntrepriseRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\ValidationService'] ??= new \App\Service\ValidationService()), ($container->privates['App\\Service\\JwtService'] ?? $container->load('getJwtServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\InvestissementApiController', $container));

        return $instance;
    }
}
