<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRendementInvestissementRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\RendementInvestissementRepository' shared autowired service.
     *
     * @return \App\Repository\RendementInvestissementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RendementInvestissementRepository'] = new \App\Repository\RendementInvestissementRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
