<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRiskScoringServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RiskScoringService' shared autowired service.
     *
     * @return \App\Service\RiskScoringService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\RiskScoringService'] = new \App\Service\RiskScoringService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
