<?php

namespace ContainerK89vGRx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTresorerieApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\TresorerieApiController' shared autowired service.
     *
     * @return \App\Controller\Api\TresorerieApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\TresorerieApiController'] = $instance = new \App\Controller\Api\TresorerieApiController(($container->privates['App\\Repository\\TresorerieRepository'] ?? $container->load('getTresorerieRepositoryService')), ($container->privates['App\\Repository\\EntrepriseRepository'] ?? $container->load('getEntrepriseRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\JwtService'] ?? $container->load('getJwtServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\TresorerieApiController', $container));

        return $instance;
    }
}
