<?php

namespace ContainerB7LiYjJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KbM2ah_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KbM2ah.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KbM2ah.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\AdminController::analytics' => ['privates', '.service_locator.mA1Y2CK', 'get_ServiceLocator_MA1Y2CKService', true],
            'App\\Controller\\Admin\\AdminController::deleteUser' => ['privates', '.service_locator.Fllgtc2', 'get_ServiceLocator_Fllgtc2Service', true],
            'App\\Controller\\Admin\\AdminController::editUser' => ['privates', '.service_locator.1UipdzX', 'get_ServiceLocator_1UipdzXService', true],
            'App\\Controller\\Admin\\AdminController::newUser' => ['privates', '.service_locator.XudNM_b', 'get_ServiceLocator_XudNMBService', true],
            'App\\Controller\\Admin\\AdminController::stats' => ['privates', '.service_locator.KjdaFpB', 'get_ServiceLocator_KjdaFpBService', true],
            'App\\Controller\\Admin\\AdminController::toggleUser' => ['privates', '.service_locator.Fllgtc2', 'get_ServiceLocator_Fllgtc2Service', true],
            'App\\Controller\\Admin\\AdminController::users' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\Front\\DashboardController::companies' => ['privates', '.service_locator.rsFN82S', 'get_ServiceLocator_RsFN82SService', true],
            'App\\Controller\\Front\\DashboardController::dashboard' => ['privates', '.service_locator.t56ggG3', 'get_ServiceLocator_T56ggG3Service', true],
            'App\\Controller\\Front\\DashboardController::profile' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\Front\\DashboardController::rendements' => ['privates', '.service_locator.Fgm2hIf', 'get_ServiceLocator_Fgm2hIfService', true],
            'App\\Controller\\Front\\DashboardController::settings' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\Front\\DashboardController::transactions' => ['privates', '.service_locator.kE.YIaG', 'get_ServiceLocator_KE_YIaGService', true],
            'App\\Controller\\Front\\DashboardController::wallets' => ['privates', '.service_locator.QYyFR91', 'get_ServiceLocator_QYyFR91Service', true],
            'App\\Controller\\InvestmentController::create' => ['privates', '.service_locator.hBvHTG3', 'get_ServiceLocator_HBvHTG3Service', true],
            'App\\Controller\\InvestmentController::delete' => ['privates', '.service_locator.9Dm3AfK', 'get_ServiceLocator_9Dm3AfKService', true],
            'App\\Controller\\InvestmentController::edit' => ['privates', '.service_locator.CPjmQhg', 'get_ServiceLocator_CPjmQhgService', true],
            'App\\Controller\\InvestmentController::index' => ['privates', '.service_locator.rlVBljV', 'get_ServiceLocator_RlVBljVService', true],
            'App\\Controller\\InvestmentController::updateStatus' => ['privates', '.service_locator.9Dm3AfK', 'get_ServiceLocator_9Dm3AfKService', true],
            'App\\Controller\\RendementController::create' => ['privates', '.service_locator.gwZ0B9m', 'get_ServiceLocator_GwZ0B9mService', true],
            'App\\Controller\\RendementController::delete' => ['privates', '.service_locator.ldY1k.X', 'get_ServiceLocator_LdY1k_XService', true],
            'App\\Controller\\RendementController::update' => ['privates', '.service_locator.gwZ0B9m', 'get_ServiceLocator_GwZ0B9mService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\AdminController:analytics' => ['privates', '.service_locator.mA1Y2CK', 'get_ServiceLocator_MA1Y2CKService', true],
            'App\\Controller\\Admin\\AdminController:deleteUser' => ['privates', '.service_locator.Fllgtc2', 'get_ServiceLocator_Fllgtc2Service', true],
            'App\\Controller\\Admin\\AdminController:editUser' => ['privates', '.service_locator.1UipdzX', 'get_ServiceLocator_1UipdzXService', true],
            'App\\Controller\\Admin\\AdminController:newUser' => ['privates', '.service_locator.XudNM_b', 'get_ServiceLocator_XudNMBService', true],
            'App\\Controller\\Admin\\AdminController:stats' => ['privates', '.service_locator.KjdaFpB', 'get_ServiceLocator_KjdaFpBService', true],
            'App\\Controller\\Admin\\AdminController:toggleUser' => ['privates', '.service_locator.Fllgtc2', 'get_ServiceLocator_Fllgtc2Service', true],
            'App\\Controller\\Admin\\AdminController:users' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\Front\\DashboardController:companies' => ['privates', '.service_locator.rsFN82S', 'get_ServiceLocator_RsFN82SService', true],
            'App\\Controller\\Front\\DashboardController:dashboard' => ['privates', '.service_locator.t56ggG3', 'get_ServiceLocator_T56ggG3Service', true],
            'App\\Controller\\Front\\DashboardController:profile' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\Front\\DashboardController:rendements' => ['privates', '.service_locator.Fgm2hIf', 'get_ServiceLocator_Fgm2hIfService', true],
            'App\\Controller\\Front\\DashboardController:settings' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\Front\\DashboardController:transactions' => ['privates', '.service_locator.kE.YIaG', 'get_ServiceLocator_KE_YIaGService', true],
            'App\\Controller\\Front\\DashboardController:wallets' => ['privates', '.service_locator.QYyFR91', 'get_ServiceLocator_QYyFR91Service', true],
            'App\\Controller\\InvestmentController:create' => ['privates', '.service_locator.hBvHTG3', 'get_ServiceLocator_HBvHTG3Service', true],
            'App\\Controller\\InvestmentController:delete' => ['privates', '.service_locator.9Dm3AfK', 'get_ServiceLocator_9Dm3AfKService', true],
            'App\\Controller\\InvestmentController:edit' => ['privates', '.service_locator.CPjmQhg', 'get_ServiceLocator_CPjmQhgService', true],
            'App\\Controller\\InvestmentController:index' => ['privates', '.service_locator.rlVBljV', 'get_ServiceLocator_RlVBljVService', true],
            'App\\Controller\\InvestmentController:updateStatus' => ['privates', '.service_locator.9Dm3AfK', 'get_ServiceLocator_9Dm3AfKService', true],
            'App\\Controller\\RendementController:create' => ['privates', '.service_locator.gwZ0B9m', 'get_ServiceLocator_GwZ0B9mService', true],
            'App\\Controller\\RendementController:delete' => ['privates', '.service_locator.ldY1k.X', 'get_ServiceLocator_LdY1k_XService', true],
            'App\\Controller\\RendementController:update' => ['privates', '.service_locator.gwZ0B9m', 'get_ServiceLocator_GwZ0B9mService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\AdminController::analytics' => '?',
            'App\\Controller\\Admin\\AdminController::deleteUser' => '?',
            'App\\Controller\\Admin\\AdminController::editUser' => '?',
            'App\\Controller\\Admin\\AdminController::newUser' => '?',
            'App\\Controller\\Admin\\AdminController::stats' => '?',
            'App\\Controller\\Admin\\AdminController::toggleUser' => '?',
            'App\\Controller\\Admin\\AdminController::users' => '?',
            'App\\Controller\\Front\\DashboardController::companies' => '?',
            'App\\Controller\\Front\\DashboardController::dashboard' => '?',
            'App\\Controller\\Front\\DashboardController::profile' => '?',
            'App\\Controller\\Front\\DashboardController::rendements' => '?',
            'App\\Controller\\Front\\DashboardController::settings' => '?',
            'App\\Controller\\Front\\DashboardController::transactions' => '?',
            'App\\Controller\\Front\\DashboardController::wallets' => '?',
            'App\\Controller\\InvestmentController::create' => '?',
            'App\\Controller\\InvestmentController::delete' => '?',
            'App\\Controller\\InvestmentController::edit' => '?',
            'App\\Controller\\InvestmentController::index' => '?',
            'App\\Controller\\InvestmentController::updateStatus' => '?',
            'App\\Controller\\RendementController::create' => '?',
            'App\\Controller\\RendementController::delete' => '?',
            'App\\Controller\\RendementController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\AdminController:analytics' => '?',
            'App\\Controller\\Admin\\AdminController:deleteUser' => '?',
            'App\\Controller\\Admin\\AdminController:editUser' => '?',
            'App\\Controller\\Admin\\AdminController:newUser' => '?',
            'App\\Controller\\Admin\\AdminController:stats' => '?',
            'App\\Controller\\Admin\\AdminController:toggleUser' => '?',
            'App\\Controller\\Admin\\AdminController:users' => '?',
            'App\\Controller\\Front\\DashboardController:companies' => '?',
            'App\\Controller\\Front\\DashboardController:dashboard' => '?',
            'App\\Controller\\Front\\DashboardController:profile' => '?',
            'App\\Controller\\Front\\DashboardController:rendements' => '?',
            'App\\Controller\\Front\\DashboardController:settings' => '?',
            'App\\Controller\\Front\\DashboardController:transactions' => '?',
            'App\\Controller\\Front\\DashboardController:wallets' => '?',
            'App\\Controller\\InvestmentController:create' => '?',
            'App\\Controller\\InvestmentController:delete' => '?',
            'App\\Controller\\InvestmentController:edit' => '?',
            'App\\Controller\\InvestmentController:index' => '?',
            'App\\Controller\\InvestmentController:updateStatus' => '?',
            'App\\Controller\\RendementController:create' => '?',
            'App\\Controller\\RendementController:delete' => '?',
            'App\\Controller\\RendementController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
