<?php

namespace ContainerB7LiYjJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CPjmQhgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CPjmQhg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CPjmQhg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'entrepriseRepository' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
            'investissement' => ['privates', '.errored..service_locator.CPjmQhg.App\\Entity\\Investissement', NULL, 'Cannot autowire service ".service_locator.CPjmQhg": it needs an instance of "App\\Entity\\Investissement" but this type has been excluded in "config/services.yaml".'],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'entityManager' => '?',
            'entrepriseRepository' => 'App\\Repository\\EntrepriseRepository',
            'investissement' => 'App\\Entity\\Investissement',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
