<?php

namespace ContainerB7LiYjJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiController' shared autowired service.
     *
     * @return \App\Controller\ApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ApiController'] = $instance = new \App\Controller\ApiController(new \App\Service\Api\NewsService(), new \App\Service\Api\ExchangeRateService(), new \App\Service\Api\AiRecommendationService(), new \App\Service\Api\AlphaVantageService(), new \App\Service\Api\WorldBankService(), ($container->privates['App\\Repository\\InvestissementRepository'] ?? $container->load('getInvestissementRepositoryService')), ($container->privates['App\\Repository\\UtilisateurRepository'] ?? $container->load('getUtilisateurRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ApiController', $container));

        return $instance;
    }
}
