<?php

namespace ContainerB7LiYjJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\OperationRepository' shared autowired service.
     *
     * @return \App\Repository\OperationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OperationRepository'] = new \App\Repository\OperationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
