<?php

namespace ContainerB7LiYjJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRendementApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\RendementApiController' shared autowired service.
     *
     * @return \App\Controller\Api\RendementApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\RendementApiController'] = $instance = new \App\Controller\Api\RendementApiController(($container->privates['App\\Repository\\RendementInvestissementRepository'] ?? $container->load('getRendementInvestissementRepositoryService')), ($container->privates['App\\Repository\\InvestissementRepository'] ?? $container->load('getInvestissementRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\JwtService'] ?? $container->load('getJwtServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\RendementApiController', $container));

        return $instance;
    }
}
