<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entreprise extends \App\Entity\Entreprise implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'capital' => [parent::class, 'capital', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'formeJuridique' => [parent::class, 'formeJuridique', null, 16],
        "\0".parent::class."\0".'idEntreprise' => [parent::class, 'idEntreprise', null, 16],
        "\0".parent::class."\0".'investissements' => [parent::class, 'investissements', null, 16],
        "\0".parent::class."\0".'latitude' => [parent::class, 'latitude', null, 16],
        "\0".parent::class."\0".'longitude' => [parent::class, 'longitude', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'proprietaire' => [parent::class, 'proprietaire', null, 16],
        "\0".parent::class."\0".'secteur' => [parent::class, 'secteur', null, 16],
        "\0".parent::class."\0".'tresoreries' => [parent::class, 'tresoreries', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'capital' => [parent::class, 'capital', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'formeJuridique' => [parent::class, 'formeJuridique', null, 16],
        'idEntreprise' => [parent::class, 'idEntreprise', null, 16],
        'investissements' => [parent::class, 'investissements', null, 16],
        'latitude' => [parent::class, 'latitude', null, 16],
        'longitude' => [parent::class, 'longitude', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'proprietaire' => [parent::class, 'proprietaire', null, 16],
        'secteur' => [parent::class, 'secteur', null, 16],
        'tresoreries' => [parent::class, 'tresoreries', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
