<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tresorerie extends \App\Entity\Tresorerie implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'derniereMaj' => [parent::class, 'derniereMaj', null, 16],
        "\0".parent::class."\0".'devise' => [parent::class, 'devise', null, 16],
        "\0".parent::class."\0".'entreprise' => [parent::class, 'entreprise', null, 16],
        "\0".parent::class."\0".'idTresorerie' => [parent::class, 'idTresorerie', null, 16],
        "\0".parent::class."\0".'nomCompte' => [parent::class, 'nomCompte', null, 16],
        "\0".parent::class."\0".'numeroCompte' => [parent::class, 'numeroCompte', null, 16],
        "\0".parent::class."\0".'rib' => [parent::class, 'rib', null, 16],
        "\0".parent::class."\0".'solde' => [parent::class, 'solde', null, 16],
        "\0".parent::class."\0".'typeCompte' => [parent::class, 'typeCompte', null, 16],
        'derniereMaj' => [parent::class, 'derniereMaj', null, 16],
        'devise' => [parent::class, 'devise', null, 16],
        'entreprise' => [parent::class, 'entreprise', null, 16],
        'idTresorerie' => [parent::class, 'idTresorerie', null, 16],
        'nomCompte' => [parent::class, 'nomCompte', null, 16],
        'numeroCompte' => [parent::class, 'numeroCompte', null, 16],
        'rib' => [parent::class, 'rib', null, 16],
        'solde' => [parent::class, 'solde', null, 16],
        'typeCompte' => [parent::class, 'typeCompte', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
