<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Investissement extends \App\Entity\Investissement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateInvestissement' => [parent::class, 'dateInvestissement', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'dureeMois' => [parent::class, 'dureeMois', null, 16],
        "\0".parent::class."\0".'entreprise' => [parent::class, 'entreprise', null, 16],
        "\0".parent::class."\0".'idInvestissement' => [parent::class, 'idInvestissement', null, 16],
        "\0".parent::class."\0".'investisseur' => [parent::class, 'investisseur', null, 16],
        "\0".parent::class."\0".'montant' => [parent::class, 'montant', null, 16],
        "\0".parent::class."\0".'rendements' => [parent::class, 'rendements', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'tauxRendementPrevu' => [parent::class, 'tauxRendementPrevu', null, 16],
        'dateInvestissement' => [parent::class, 'dateInvestissement', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'dureeMois' => [parent::class, 'dureeMois', null, 16],
        'entreprise' => [parent::class, 'entreprise', null, 16],
        'idInvestissement' => [parent::class, 'idInvestissement', null, 16],
        'investisseur' => [parent::class, 'investisseur', null, 16],
        'montant' => [parent::class, 'montant', null, 16],
        'rendements' => [parent::class, 'rendements', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'tauxRendementPrevu' => [parent::class, 'tauxRendementPrevu', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
