<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null, 16],
        "\0".parent::class."\0".'budget' => [parent::class, 'budget', null, 16],
        "\0".parent::class."\0".'cin' => [parent::class, 'cin', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'entreprises' => [parent::class, 'entreprises', null, 16],
        "\0".parent::class."\0".'faceImage' => [parent::class, 'faceImage', null, 16],
        "\0".parent::class."\0".'highestProfit' => [parent::class, 'highestProfit', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'investissements' => [parent::class, 'investissements', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null, 16],
        "\0".parent::class."\0".'userKyc' => [parent::class, 'userKyc', null, 16],
        "\0".parent::class."\0".'yearsExperience' => [parent::class, 'yearsExperience', null, 16],
        'active' => [parent::class, 'active', null, 16],
        'budget' => [parent::class, 'budget', null, 16],
        'cin' => [parent::class, 'cin', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'entreprises' => [parent::class, 'entreprises', null, 16],
        'faceImage' => [parent::class, 'faceImage', null, 16],
        'highestProfit' => [parent::class, 'highestProfit', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'investissements' => [parent::class, 'investissements', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'tel' => [parent::class, 'tel', null, 16],
        'userKyc' => [parent::class, 'userKyc', null, 16],
        'yearsExperience' => [parent::class, 'yearsExperience', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
