<?php

namespace Container1wSmeeE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9Dm3AfKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9Dm3AfK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9Dm3AfK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'investissement' => ['privates', '.errored..service_locator.9Dm3AfK.App\\Entity\\Investissement', NULL, 'Cannot autowire service ".service_locator.9Dm3AfK": it needs an instance of "App\\Entity\\Investissement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'investissement' => 'App\\Entity\\Investissement',
        ]);
    }
}
