<?php

namespace Container7WESYgC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GwZ0B9mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gwZ0B9m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gwZ0B9m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'investissementRepository' => ['privates', 'App\\Repository\\InvestissementRepository', 'getInvestissementRepositoryService', true],
            'rendementRepository' => ['privates', 'App\\Repository\\RendementInvestissementRepository', 'getRendementInvestissementRepositoryService', true],
        ], [
            'entityManager' => '?',
            'investissementRepository' => 'App\\Repository\\InvestissementRepository',
            'rendementRepository' => 'App\\Repository\\RendementInvestissementRepository',
        ]);
    }
}
