<?php

namespace Container7WESYgC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExternalApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\ExternalApiController' shared autowired service.
     *
     * @return \App\Controller\Api\ExternalApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\ExternalApiController'] = $instance = new \App\Controller\Api\ExternalApiController(($container->privates['App\\Service\\JwtService'] ?? $container->load('getJwtServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\ExternalApiController', $container));

        return $instance;
    }
}
