<?php

namespace Container7WESYgC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvestissementRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\InvestissementRepository' shared autowired service.
     *
     * @return \App\Repository\InvestissementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\InvestissementRepository'] = new \App\Repository\InvestissementRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
