<?php

namespace Container7WESYgC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJwtServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\JwtService' shared autowired service.
     *
     * @return \App\Service\JwtService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\JwtService'] = new \App\Service\JwtService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
