<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSXXBo5p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSXXBo5p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSXXBo5p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSXXBo5p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSXXBo5p\App_KernelDevDebugContainer([
    'container.build_hash' => 'SXXBo5p',
    'container.build_id' => 'cd956ebb',
    'container.build_time' => 1775348187,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSXXBo5p');
